apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swarmsre-server.fullname" . }}
  labels:
    {{- include "swarmsre-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  databaseUrl: "postgresql://swarmsre:swarmsre@{{ include "swarmsre-server.fullname" . }}-postgres:5432/swarmsre"
  {{- else }}
  databaseUrl: {{ required "A valid config.databaseUrl is required if postgresql.enabled is false" .Values.config.databaseUrl | quote }}
  {{- end }}
  openaiApiKey: {{ required "A valid config.openaiApiKey is required" .Values.config.openaiApiKey | quote }}
  slackWebhookUrl: {{ .Values.config.slackWebhookUrl | default "" | quote }}
