apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-{{ .Values.rbac.profile }}
rules:
{{- if eq .Values.rbac.profile "readonly" }}
  - apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
{{- else if eq .Values.rbac.profile "standard" }}
  - apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "patch", "update"]
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-{{ .Values.rbac.profile }}
  apiGroup: rbac.authorization.k8s.io
