apiVersion: v1
entries:
  swarmsre-server:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-08-24T06:37:22.939019862Z"
    description: A Helm chart for Kubernetes
    digest: 2a62978d40c60e89588467fe0e8cb785656606d6b01a730a8258b977f6a8b9cf
    name: swarmsre-server
    type: application
    urls:
    - https://get.swarmsre.app/charts/swarmsre-server-0.1.0.tgz
    version: 0.1.0
generated: "2026-08-24T06:37:22.938541002Z"
