apiVersion: v1
kind: Namespace
metadata:
  name: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: nginx:latest
        command: ["/bin/sh", "-c"]
        args: ["echo 'Simulating a crash...'; exit 1"]
